# pyre-unsafe
"""JSON and Markdown report exporter."""

from __future__ import annotations

import json
from datetime import datetime

from cyber_sentry_cli.core.models import Run


def export_json(run: Run) -> str:
    """Export run as formatted JSON."""
    return run.model_dump_json(indent=2)


def export_markdown(run: Run) -> str:
    """Export run as a Markdown report."""
    lines: list[str] = []

    lines.append(f"# 🛡️ CyberSentry Scan Report")
    lines.append(f"")
    lines.append(f"**Run ID:** `{run.id}`")
    lines.append(f"**Target:** `{run.target}`")
    lines.append(f"**Started:** {run.started_at}")
    lines.append(f"**Completed:** {run.completed_at or 'In Progress'}")
    lines.append(f"**Status:** {run.status}")
    lines.append(f"**Scanners:** {', '.join(run.scanners_used)}")
    lines.append(f"**Total Findings:** {run.total_findings}")
    lines.append("")

    # Severity summary
    from collections import Counter
    sev_counts = Counter(f.severity.value for f in run.findings)
    lines.append("## 📊 Severity Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        if sev in sev_counts:
            lines.append(f"| {sev} | {sev_counts[sev]} |")
    lines.append("")

    # Findings
    if run.findings:
        lines.append("## 🔍 Findings")
        lines.append("")
        for i, f in enumerate(run.findings, 1):
            lines.append(f"### {i}. [{f.severity.value}] {f.title}")
            lines.append(f"")
            lines.append(f"- **ID:** `{f.id}`")
            lines.append(f"- **Scanner:** {f.scanner}")
            lines.append(f"- **Rule:** `{f.rule_id}`")
            lines.append(f"- **CWE:** {f.cwe or 'N/A'}")
            lines.append(f"- **File:** `{f.file_path}:{f.line_start}`")
            lines.append(f"- **Confidence:** {f.confidence:.0%}")
            lines.append(f"")
            if f.description:
                lines.append(f"> {f.description}")
                lines.append("")
            if f.code_snippet:
                lines.append(f"```python")
                lines.append(f"{f.code_snippet}")
                lines.append(f"```")
                lines.append("")

    # Clusters
    if run.clusters:
        lines.append("## 📊 Root Cause Clusters")
        lines.append("")
        for i, c in enumerate(run.clusters, 1):
            lines.append(f"### Cluster {i}: {c.root_cause}")
            lines.append(f"- **Risk Score:** {c.risk_score:.2f}")
            lines.append(f"- **Findings:** {len(c.finding_ids)}")
            lines.append(f"- **Reasoning:** {c.reasoning}")
            lines.append("")

    lines.append("---")
    lines.append(f"*Generated by CyberSentry v0.1.0 at {datetime.utcnow().isoformat()}*")

    return "\n".join(lines)
